"""
axes.py -- the three orthogonal prompt axes: MOTION family, CAMERA move, AUDIO fence.

Vendored VERBATIM from vector-lab insta_ltx.py (extracted by AST, not retyped) on
2026-07-10; this copy is authoritative for the node. The inert defaults inject NOTHING:
motion "free" (the model reads the beats and decides -- a multi-beat story is never
forced into one family), camera "free" (the model chooses the camera from the frame),
audio "full" (the model authors all audio layers freely). Every other choice injects one
positive, authoritative directive block into the vision prompt -- exactly as the
director_ltx CLI does.
"""


MOTION_CORES = {
    'impact': 'MOTION TYPE: IMPACT.\nONE thing strikes another and the moment of contact is the peak. The impact can be\nPHYSICAL (a hand slamming a surface, a fist landing a punch, a foot\nstomping, a hammer hitting, an object dropped onto a table) OR an ENERGY / VFX hit\n(a projectile flying, a weapon released, a bolt of energy or a shockwave bursting) --\nread the frame and pick whichever the image actually shows; keep a plainly physical\nhit physical -- energy, glow or VFX appear ONLY when the frame already shows them.\nApart from the striking thing (and what recoils at the point of contact), every\nfigure stays frozen in pose. Keep it punchy -- a sudden sharp change at the instant\nof contact.\n\nField roles for impact:\n- mover: the ONE thing that strikes (the hand / fist / foot / falling object, OR\n  the arrow / energy / shock) -- named by colour + frame-position.\n- transition: the wind-up / approach motion that leads to contact (the hand rising\n  then driving down, the arm cocking, the projectile streaking in). Brief, building.\n- impact: the sudden peak AT CONTACT -- for a physical hit, the slap / thud / jolt and\n  how the struck surface or body reacts (the paper crinkling and jumping, dust puffing,\n  the body recoiling); for an energy hit, the burst / shockwave at the target. Match\n  the reaction to the scale of what was struck -- paper crinkles and lifts, a body\n  recoils, a hard surface jolts.\n- held_still: which figures / elements hold their posture locked in place.',
    'dialogue': 'MOTION TYPE: DIALOGUE.\nTwo figures (or a figure and an unseen addressee) speak. The motion is small and\nintimate: lips move with the line, head tilts as a thought lands, a hand rises\nslightly to point or settle. Eyes lock on the addressee. The bodies stay grounded\nand still in their established pose.\n\nField roles for dialogue:\n- mover: the speaker (named by colour + frame-position) and the small gestures they\n  make as they speak.\n- transition: the line(s) being spoken in order, present tense, with the physical\n  beats between words ("the seated figure in ochre tilts his head, then speaks").\n- impact: the moment the line LANDS -- the listener\'s face responds (eyes widen\n  slightly, jaw relaxes, head bows). Low-key and gentle.\n- held_still: bodies and hands that stay locked in their existing pose during the\n  exchange.',
    'expression': 'MOTION TYPE: EXPRESSION.\nOne figure\'s INNER STATE shifts visibly across the clip -- recognition, grief,\nresolve, awe, fear settling, anger gathering. The motion lives in the face: eyes\nnarrow / widen / well up / steady; jaw clenches / relaxes; lips part slightly,\npress together; a single tear forms; a slow nod; a hand drifts up to chest or\nmouth. Intimate close-up register. The surroundings stay calm and still.\n\nField roles for expression:\n- mover: the part of the face / body that changes (the eyes, the jaw, the mouth,\n  the hand at the chest).\n- transition: the inner-state shift rendered as visible physical beats, in order\n  ("the eyes lower, then steady, then lift again with a slow breath").\n- impact: the moment the shift LANDS -- the final settled expression at the end of\n  the clip. Low-key and settled.\n- held_still: the rest of the body and environment that stays locked.',
    'ritual': 'MOTION TYPE: RITUAL (DELIBERATE GESTURE).\nA slow, deliberate hands-led gesture is performed and a substance or object responds.\nThis is ANY careful ceremonial or craft action -- pour a liquid, light a flame, raise\nor place an offering, mix and plate a dish, fold the hands, anoint or apply something,\nset an object down with care -- read the frame for which one it is. The thing acted on\nresponds: smoke or steam rises, a flame catches and surges, liquid threads down,\npetals or grains scatter, a surface settles. Reverent, measured pacing, deliberate\nhands. The gesture resolves gently.\n\nField roles for ritual:\n- mover: the hands performing the gesture + the substance / object that responds (the\n  pouring liquid, the rising smoke, the catching flame).\n- transition: the gesture in order, present tense, slow ("the hands lift the vessel,\n  the stream descends, the flame surges to meet it").\n- impact: the moment of the gesture\'s completion -- the pour finished, the flame lit,\n  the offering placed, the hands settled. Resolved and calm.\n- held_still: the figures and surroundings that stay locked through the gesture.',
    'journey': 'MOTION TYPE: JOURNEY.\nFigures walk / ride / process through landscape. The legs move, fabric sways, the\nground passes underfoot. This is the one motion type where \'characters walking\' and\n\'feet moving\' are CORRECT and expected here.\n\nField roles for journey:\n- mover: the walking / riding figures (by colour + frame-position) + their gait\n  beats (steps, sway, the procession\'s rhythm).\n- transition: the movement through the setting in present tense ("the figures walk\n  forward along the path, dust rising at their heels, the surroundings drifting past\n  behind them").\n- impact: the moment the journey reaches a beat -- cresting a rise, passing through a\n  gateway or doorway, the lead figure pausing as the destination becomes visible.\n  Low-key and quiet.\n- held_still: the landscape elements that stay framed (mountains in the distance,\n  fixed trees, the dirt path itself).',
    'ambient': 'MOTION TYPE: AMBIENT (LIVING TABLEAU).\nEvery figure holds pose; only elemental ambience moves -- wind in cloth / hair /\nbanners, ember sparks rising, water lapping the bank, mist or smoke drifting,\ncandle / fire flicker, dust motes in shafts of light, subtle breath in chests. The\nfirst and last frame are essentially identical: the still breathes for ~10s and\nreturns to rest.\n\nField roles for ambient:\n- mover: the ONE ambient element that moves (e.g. "the flame of the hearth", "the\n  banner cloth", "the river\'s surface", "the rising ember smoke").\n- transition: the ~10s ambient breathing in present tense -- the flame\n  flickering, the banner snapping, the smoke drifting. LIVING PRESENCE, a quiet\n  continuous breathing.\n- impact: the most-alive instant of the ambient motion (the highest flame-lick,\n  the fullest banner-snap, the densest ember shower). A peak of LIVENESS -- the\n  most alive the ambience gets.\n- held_still: every figure holds their posture locked in place.',
    'free': '',
    'reveal': 'MOTION TYPE: REVEAL (MANIFESTATION).\nSomething / someone appears, resolves, or clarifies -- mist clears to expose a\nfigure; particles of golden light condense into a humanoid form; a stone shell\ncracks and a figure emerges; a divine figure descends through cloud. Slow build.\nThe reveal motion is gradual and reverent, a calm manifestation.\n\nField roles for reveal:\n- mover: the thing being revealed (the figure forming, the mist clearing, the\n  light condensing).\n- transition: the gradual resolution in order ("particles of warm gold light\n  drift inward toward the centre, condensing into a humanoid form; the form\n  solidifies from the crown downward, attire settling last").\n- impact: the moment the reveal RESOLVES -- the figure now fully present, the\n  mist fully gone, eyes opening. Peaceful resolution.\n- held_still: the surrounding figures who witness, holding their posture.',
}

CAMERA_CORES = {
    'free': '',
    'push_in': 'CAMERA DIRECTIVE -- push in (this OVERRIDES any camera the action implies):\nThe camera performs ONE slow dolly in, gliding steadily toward the subject so the frame\ntightens and the moment grows more intimate. Name where the push ENDS -- the face, the hands,\nthe object it closes on -- and what fills the frame as it arrives. This dolly in is the ONLY\ncamera move; the camera holds otherwise steady.\n\n',
    'dolly_out': 'CAMERA DIRECTIVE -- dolly out / pull back (this OVERRIDES any camera the action implies):\nThe camera performs ONE slow dolly out, pulling steadily back from the subject to reveal the\nwider scene. Describe the DESTINATION of the pull-back and what it UNCOVERS as the frame\nwidens -- the surrounding space, the figures or landscape that come into view at the edges.\nThis dolly out is the ONLY camera move; the camera holds otherwise steady.\n\n',
    'pan': 'CAMERA DIRECTIVE -- pan (this OVERRIDES any camera the action implies):\nThe camera performs ONE slow pan, rotating horizontally to sweep across the scene; state the\ndirection (pan left or pan right) and what slides into frame as it sweeps. The horizon stays\nlevel. This pan is the ONLY camera move; the camera holds otherwise steady.\n\n',
    'dolly_left': 'CAMERA DIRECTIVE -- dolly left (this OVERRIDES any camera the action implies):\nThe camera performs ONE slow dolly left, the whole camera gliding laterally to the left,\nparallel to the subject, the foreground sliding past against the background. This dolly left\nis the ONLY camera move; the camera holds otherwise steady.\n\n',
    'dolly_right': 'CAMERA DIRECTIVE -- dolly right (this OVERRIDES any camera the action implies):\nThe camera performs ONE slow dolly right, the whole camera gliding laterally to the right,\nparallel to the subject, the foreground sliding past against the background. This dolly right\nis the ONLY camera move; the camera holds otherwise steady.\n\n',
    'jib_up': 'CAMERA DIRECTIVE -- jib up (this OVERRIDES any camera the action implies):\nThe camera performs ONE slow jib up, the whole camera rising vertically while it keeps facing\nthe subject, lifting the viewpoint over the scene. This jib up is the ONLY camera move; the\ncamera holds otherwise steady.\n\n',
    'jib_down': 'CAMERA DIRECTIVE -- jib down (this OVERRIDES any camera the action implies):\nThe camera performs ONE slow jib down, the whole camera descending vertically while it keeps\nfacing the subject, lowering the viewpoint toward the scene. This jib down is the ONLY camera\nmove; the camera holds otherwise steady.\n\n',
    'tilt': 'CAMERA DIRECTIVE -- tilt (this OVERRIDES any camera the action implies):\nThe camera performs ONE slow tilt, the lens pivoting up or down from a fixed position; state\nthe direction (tilt up or tilt down) and what comes into frame as the lens pivots. This tilt\nis the ONLY camera move; the camera holds otherwise steady.\n\n',
    'orbit': 'CAMERA DIRECTIVE -- orbit (this OVERRIDES any camera the action implies):\nThe camera performs ONE slow orbit, circling around the central subject while holding focus\non it, the background sweeping behind as the angle changes. Name where the orbit travels and\nwhat new side of the subject and scene it reveals. This orbit is the ONLY camera move; the\ncamera holds otherwise steady.\n\n',
    'rack_focus': 'CAMERA DIRECTIVE -- rack focus (this OVERRIDES any camera the action implies):\nThe camera stays put and shifts its FOCAL PLANE -- the focus travels from one subject to\nanother within the frame (foreground to background, or one figure to another), the first\nsoftening as the second sharpens. State which element starts sharp and which ends sharp.\nThis focus pull is the ONLY camera change; the camera body holds still.\n\n',
}

AUDIO_DIRECTIVES = {
    'full': '',
    'dialog-only': 'AUDIO LOCK -- dialog-only (this OVERRIDES any audio a motion family might imply):\nThe ONLY sound in this clip is the clean spoken DIALOGUE itself -- dry, isolated voices over\ntotal silence, as if recorded close in a sound booth. One OR MORE characters may speak (an\non-screen voice, an off-screen voice, several voices); whatever is spoken is the only audio.\nThere is no room tone, no ambient bed, no cavern hum, no air or environmental sound; there\nare no foley or action sound effects (no footsteps, no taps, no scrapes, no rustle); there is\nno music, score, song, instrument or musical tone of any kind. Nothing plays under or around\nthe voices -- only the spoken line(s) over silence. You still choose freely WHO speaks, WHAT\nis said, and HOW each voice sounds.\n\n',
    'ambient-only': "AUDIO LOCK -- ambient-only (this OVERRIDES any audio a motion family might imply):\nThe audio is the place's natural ambient bed plus time-aligned sound effects ALONE -- the\nactual sounds the scene and its motion make. The clip carries no spoken dialogue and no\nmusic, score, song or instrument of any kind. You still choose freely WHICH real-world\nambient sounds and effects fit what is on screen.\n\n",
    'silent': 'AUDIO LOCK -- silent (this OVERRIDES any audio a motion family might imply):\nThe audio is a quiet natural ambient bed ONLY -- the faint resting tone of the space.\nThere is no spoken dialogue, no music or score, and no sharp sound-effect peaks; the\nsoundtrack stays low and still. You still choose freely WHAT that quiet ambient tone is.\n\n',
    'no-music': "AUDIO LOCK -- no-music (this OVERRIDES any audio a motion family might imply):\nThe soundtrack is fully DIEGETIC: the spoken DIALOGUE, the place's natural ambient bed, and\ntime-aligned foley and sound effects -- all the real sounds the scene and its motion make.\nThere is NO music, score, song, instrument or musical tone of any kind; nothing musical\nplays under or around the action. You still choose freely WHO speaks, WHAT is said, HOW each\nvoice sounds, and WHICH ambient sounds and effects fit what is on screen.\n\n",
}

MOTION_CHOICES = list(MOTION_CORES.keys())
CAMERA_CHOICES = list(CAMERA_CORES.keys())
AUDIO_CHOICES = list(AUDIO_DIRECTIVES.keys())
